hashi/bookkeeping/urls.py
from bookkeeping import views
from django.urls import path

app_name = "bookkeeping"

urlpatterns = [
    path("", views.entry_list, name="entry-list"),
]

hashi/hashi/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("bookkeeping/", include("bookkeeping.urls", namespace="bookkeeping")),
    path("django-rq/", include("django_rq.urls")),
    path("webhooks/", include("webhooks.urls", namespace="webhooks")),
]

hashi/webhooks/urls.py
from django.urls import path
from webhooks import views

app_name = "webhooks"

urlpatterns = [
    path("paypal", views.paypal_listener, name="paypal-ipn-listener"),
]

hashi/bookkeeping/models.py
from django.db import models


class EntryType(models.IntegerChoices):
    INCOME = 1, "INCOME"
    EXPENSE = 2, "EXPENSE"
    TRANSFER = 3, "TRANSFER"  # Value transfer between accounts


class Account(models.Model):
    name = models.CharField(max_length=12, unique=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=12, unique=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Entry(models.Model):
    date = models.DateField()
    value = models.DecimalField(max_digits=10, decimal_places=2)
    type = models.PositiveSmallIntegerField(choices=EntryType.choices)
    account = models.ForeignKey(Account, null=True, on_delete=models.SET_NULL)
    description = models.CharField(max_length=128)
    tags = models.ManyToManyField(Tag, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "entries"


def new_entry(date, value, type, description, account_name, tags=None):
    account = Account.objects.filter(name=account_name).first()
    if account is None:
        raise ValueError(f"Unable to find an Account with name '{account_name}'")

    entry = Entry.objects.create(
        date=date,
        value=value,
        type=type,
        description=description,
        account=account,
    )
    if tags is not None:
        for tag_name in tags:
            tag, _ = Tag.objects.get_or_create(name=tag_name)
            entry.tags.add(tag)

    return entry

hashi/webhooks/models.py
from django.db import models


class GatewayType(models.IntegerChoices):
    PAYPAL = 1, "PAYPAL"


class NotificationStatus(models.IntegerChoices):
    RECEIVED = 1, "RECEIVED"
    VERIFIED = 2, "VERIFIED"
    INVALID = 3, "INVALID"


class Notification(models.Model):
    gateway = models.PositiveSmallIntegerField(choices=GatewayType.choices)
    raw_notification = models.TextField()
    status = models.PositiveSmallIntegerField(
        choices=NotificationStatus.choices, default=NotificationStatus.RECEIVED
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

hashi/bookkeeping/views.py
from bookkeeping.models import Entry, EntryType
from django.db.models import Sum
from django.shortcuts import render
from django.utils import timezone


def entry_list(request):
    today = timezone.now()
    month = request.GET.get("month") or today.month
    year = request.GET.get("year") or today.year
    entries = Entry.objects.exclude(type=EntryType.TRANSFER).filter(
        date__month=month, date__year=year
    )

    total_expense, total_income = 0, 0
    for entry in entries.values("type").annotate(total_value=Sum("value")):
        if entry["type"] == EntryType.INCOME.value:
            total_income = entry["total_value"]
        elif entry["type"] == EntryType.EXPENSE.value:
            total_expense = entry["total_value"]

    context = {
        "entries": entries,
        "total_income": total_income,
        "total_expense": total_expense,
        "balance": total_income - total_expense,
        "month": int(month),
        "year": year,
        "month_range": range(1, 13),
    }
    return render(request, "bookkeeping/entry_list.html", context=context)

hashi/webhooks/views.py
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from webhooks.models import GatewayType, Notification
from webhooks.utils import paypal_handshake


@csrf_exempt
def paypal_listener(request):
    raw_notification = request.body.decode("utf-8")
    notification = Notification.objects.create(
        gateway=GatewayType.PAYPAL, raw_notification=raw_notification
    )
    paypal_handshake.delay(notification)
    return HttpResponse("")

hashi/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hashi</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/css/adminlte.min.css">
  </head>

  <body class="hold-transition sidebar-mini">
    <div class="wrapper">
      {% block navbar %}
      <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
          </li>
          <li class="nav-item d-none d-sm-inline-block">
            <a href="" class="nav-link">Home</a>
          </li>
        </ul>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
              <i class="fas fa-expand-arrows-alt"></i>
            </a>
          </li>
        </ul>
      </nav>
      {% endblock %}

      {% block sidebar %}
      <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="index3.html" class="brand-link">
          <span class="brand-text font-weight-light">Hashi</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
          <!-- Sidebar Menu -->
          <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon fas fa-comments-dollar"></i>
                  <p>
                    Bookkeeping
                  </p>
                </a>
              </li>
            </ul>
          </nav>
          <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
      </aside>
      {% endblock %}

      <div class="content-wrapper">
        {% block content-header %}
        <div class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1 class="m-0">Starter Page</h1>
              </div><!-- /.col -->
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li class="breadcrumb-item active">Bookkeeping</li>
                </ol>
              </div><!-- /.col -->
            </div><!-- /.row -->
          </div><!-- /.container-fluid -->
        </div>
        {% endblock %}

        {% block content-main %}{% endblock %}
      </div>

      {% block footer %}
      <footer class="main-footer">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
          Theory is when you know everything but nothing works. Practice is when everything works
          but no one knows why. Around here, theory and practice are combined: nothing works and no
          one knows why.
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2021</strong> All rights reserved.
      </footer>
      {% endblock %}
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.1/js/bootstrap.min.js" integrity="sha512-UR25UO94eTnCVwjbXozyeVd6ZqpaAE9naiEUBK/A+QDbfSTQFhPGj5lOR6d8tsgbBk84Ggb5A3EkjsOgPRPcKA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/js/adminlte.min.js"></script>
  </body>
</html>

hashi/templates/bookkeeping/entry_list.html
{% extends "base.html" %}

{% block content-main %}
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card-body">
          <ul class="pagination pagination-month justify-content-center">
            <li class="page-item">
              <a class="page-link" href="{% url 'bookkeeping:entry-list' %}?month=12&year={{ year|add:'-1' }}">«</a>
            </li>
            {% for month_ in month_range %}
              {% if month == month_ %}
              <li class="page-item active">
              {% else %}
              <li class="page-item">
              {% endif %}
                <a class="page-link" href="{% url 'bookkeeping:entry-list' %}?month={{ month_ }}&year={{ year }}">
                  <p class="page-month">{{ month_|stringformat:"02d" }}</p>
                  <p class="page-year">{{ year }}</p>
                </a>
              </li>
            {% endfor %}
            <li class="page-item">
              <a class="page-link" href="{% url 'bookkeeping:entry-list' %}?month=1&year={{ year|add:'1' }}">»</a>
            </li>
          </ul>
        </div>

        <table class="table table-hover">
          <thead>
            <tr>
              <td></td>
              <td>
                <span class="text-success">+{{ total_income|floatformat:2 }}</span><br/>
                <span class="text-danger">-{{ total_expense|floatformat:2 }}</span>
              </td>
              <td colspan="3">
                {% if balance < 0 %}
                  <strong><span class="text-danger">{{ balance|floatformat:2 }}</span></strong>
                {% else %}
                  <strong><span class="text-success">{{ balance|floatformat:2 }}</span></strong>
                {% endif %}
              </td>
            </tr>
            <tr>
              <th>Date</th>
              <th>Value</th>
              <th>Description</th>
              <th>Account</th>
              <th>Tags</th>
            </tr>
          </thead>
          <tbody>
            {% for entry in entries %}
            <tr>
              <td>{{ entry.date }}</td>
              <td>
                <span class="{{ entry.get_type_display|lower }}">
                  {% if entry.get_type_display == "EXPENSE" %}-{% endif %}{{ entry.value }}
                </span>
              </td>
              <td>{{ entry.description }}</td>
              <td>
                <span class="badge bg-danger">{{ entry.account.name }}</span>
              </td>
              <td>
                {% for tag in entry.tags.all %}
                  <span class="badge bg-success">{{ tag.name }}</span>
                {% endfor %}
              </td>
            </tr>
            {% empty %}
            <tr>
              <td colspan="5">No entries found!</td>
            </tr>
            {% endfor %}
            <tr>
              <td></td>
              <td>
                <span class="text-success">+{{ total_income|floatformat:2 }}</span><br/>
                <span class="text-danger">-{{ total_expense|floatformat:2 }}</span>
              </td>
              <td colspan="3">
                {% if balance < 0 %}
                  <strong><span class="text-danger">{{ balance|floatformat:2 }}</span></strong>
                {% else %}
                  <strong><span class="text-success">{{ balance|floatformat:2 }}</span></strong>
                {% endif %}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</div>
{% endblock %}